# Generated by Django 4.2.4 on 2023-10-11 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskdata',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
